name: Deploy to PyPi

on: 
  release:
      types: [created]

jobs:
  build_and_deploy:
    name: Build the release and deploy to test pypi
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install main dependencies
        run: |
          python -m pip install --upgrade pip twine setuptools wheel

      - name: build distribution
        run: |
          python setup.py sdist bdist_wheel

      - name: test install package
        run: |
          pip install -e .

      - name: Publish distribution 📦 to  PyPI

        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip_existing: true
          verbose: true
          password: ${{ secrets.SHAFT_PYPI_PW }}
          repository_url: https://upload.pypi.org/legacy/