# name: Deploy to Test PyPi

# on: 
#   push:
#       branches:
#         - dev
# jobs:
#   build_and_deploy:
#     name: Build the release and deploy to test pypi
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - name: Set up Python 3.8
#         uses: actions/setup-python@v1
#         with:
#           python-version: 3.8
#       - name: Cache pip
#         uses: actions/cache@v2

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip twine setuptools
#           pip setup.py sdist bdist_wheel
#       - name: Install package
#         run: |
#           pip install . -U
#           python setup.py sdist
#       - name: Upload
#         uses: pypa/gh-action-pypi-publish@dev
#         with:
#           skip_existing: true
#           user: __token__
#           password: ${{ secrets.SHAFT_PYPI_TEST }}
#           repository_url: https://test.pypi.org/legacy/

name: Publish Python 🐍 distributions 📦 to PyPI and TestPyPI

on: 
  push:
      branches:
        - dev

jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI and TestPyPI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip twine setuptools
          pip setup.py sdist bdist_wheel
      - name: Install package
        run: |
          pip install . -U
          python setup.py sdist

    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.SHAFT_PYPI_TEST }}
        repository_url: https://test.pypi.org/legacy/