name: Deploy to PyPi

on: 
  release:
      types: [created]

jobs:
<<<<<<< HEAD
  build-n-publish:
    name: Build the release
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
=======
  build:
    name: Build the release
    runs-on: ubuntu-latest
>>>>>>> dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.8

        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Cache pip
        uses: actions/cache@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install package
        run: |
          pip install . -U
          python setup.py sdist
      - name: Upload

        uses: pypa/gh-action-pypi-publish@dev
        with:
          user: __token__
          password: ${{ secrets.SHAFT_PYPI_PW }}